Repository FlexibleSUSY/FlexibleSUSY, pull requests merged in 2024-01, with the labels that each got.

#589 configure can locate Lilith
  .github/workflows/tests.yml
  config/Makefile.in
  config/config.h.in
  configure
  src/module.mk
  templates/module.mk.in
Labels: enhancement

#592 Feature: Allow user to specify WolframEngine for installation
  install-sarah
Labels: enhancement

#595 Bugfix: Time delay in update_module_mk
  configure
Labels: bug

#571 Feature: Improved uncertainty estimate of AMM
  meta/AMM.m
  meta/FlexibleSUSY.m
  templates/amm.cpp.in
  test/test_CMSSMNoFV_GM2Calc.sh
  test/test_MRSSM2_amm.cpp
  test/test_THDMII_GM2Calc.sh
Labels: bug, enhancement
